INSERT INTO ligas (cod_liga, nombre, pais) VALUES (1, 'LALIGA EA SPORTS', 'España');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (2, 'Premier League', 'Inglaterra');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (3, 'Bundesliga', 'Alemania');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (4, 'Ligue 1 McDonald''s', 'Francia');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (5, 'Serie A Enilive', 'Italia');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (6, 'MLS', 'Estados Unidos');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (7, 'ROSHN Saudi League', 'Arabia Saudita');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (8, 'Liga Portugal', 'Portugal');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (9, 'Libertadores', 'Sudamérica');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (10, 'Serie BKT', 'Italia');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (11, 'Trendyol Süper Lig', 'Turquía');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (12, 'Eredivisie', 'Países Bajos');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (13, '1A Pro League', 'Bélgica');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (14, 'Liga Hrvatska', 'Croacia');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (15, 'Scottish Prem', 'Escocia');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (16, 'Primera División', 'España');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (17, 'Hellas Liga', 'Grecia');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (18, 'United Emirates League', 'Emiratos Árabes Unidos');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (19, 'Česká Liga', 'República Checa');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (20, 'Magyar Liga', 'Hungría');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (21, 'CSL', 'China');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (22, 'Sudamericana', 'Sudamérica');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (23, 'Ukrayina Liha', 'Ucrania');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (24, 'LALIGA HYPERMOTION', 'España');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (25, 'Ö. Bundesliga', 'Austria');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (26, 'EFL Championship', 'Inglaterra');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (27, 'Ligue 2 BKT', 'Francia');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (28, 'Liga Colombia', 'Colombia');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (29, 'Bundesliga 2', 'Alemania');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (30, 'Eliteserien', 'Noruega');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (31, '3F Superliga', 'Dinamarca');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (32, 'K League 1', 'Corea del Sur');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (33, 'CSSL', 'India');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (34, 'PKO BP Ekstraklasa', 'Polonia');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (35, 'A-League', 'Australia');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (36, 'Allsvenskan', 'Suecia');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (37, 'Liga Cyprus', 'Chipre');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (38, 'Liga Azerbaijan', 'Azerbaiyán');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (39, 'SUPERLIGA', 'Serbia');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (40, 'EFL League One', 'Inglaterra');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (41, 'ISL', 'India');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (42, '3. Liga', 'Alemania');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (43, 'SSE Airtricity PD', 'Irlanda');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (44, 'EFL League Two', 'Inglaterra');
INSERT INTO ligas (cod_liga, nombre, pais) VALUES (45, 'Finnliiga', 'Finlandia');
