INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (1, 'Real Madrid', 1);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (2, 'Manchester City', 2);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (3, 'FC Bayern München', 3);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (4, 'Arsenal', 2);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (5, 'Paris SG', 4);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (6, 'Liverpool', 2);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (7, 'Lombardia FC', 1);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (8, 'FC Barcelona', 1);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (9, 'Inter Miami CF', 6);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (10, 'Atlético de Madrid', 1);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (11, 'Leverkusen', 3);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (12, 'Borussia Dortmund', 3);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (13, 'SSC Napoli', 5);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (14, 'AS Roma', 5);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (15, 'Milano FC', 5);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (16, 'Al Hilal', 7);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (17, 'Man Utd', 2);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (18, 'Spurs', 2);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (19, 'Aston Villa', 2);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (20, 'Al Nassr', 7);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (21, 'Al Ittihad', 7);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (22, 'Juventus', 5);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (23, 'Athletic Club', 1);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (24, 'Newcastle Utd', 2);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (25, 'Al Ahli', 7);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (26, 'Valencia CF', 1);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (27, 'RB Leipzig', 3);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (28, 'Chelsea', 2);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (29, 'RC Celta', 1);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (30, 'Sporting CP', 8);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (31, 'FC Porto', 8);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (32, 'Real Sociedad', 1);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (33, 'River Plate', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (34, 'Sassuolo', 5);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (35, 'Al Shabab', 7);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (36, 'SL Benfica', 8);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (37, 'Fenerbahçe', 7);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (38, 'Beşiktaş', 7);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (39, 'LAFC', 6);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (40, 'Galatasaray', 7);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (41, 'Villarreal CF', 1);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (42, 'Everton', 2);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (43, 'Latium', 5);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (44, 'West Ham', 2);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (45, 'Girona FC', 1);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (46, 'Torino', 5);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (47, 'Real Betis', 1);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (48, 'Al Qadisiyah', 7);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (49, 'TSG Hoffenheim', 3);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (50, 'Bergamo Calcio', 5);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (51, 'RCD Mallorca', 1);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (52, 'SC Freiburg', 3);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (53, 'OL', 1);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (54, 'Fulham', 2);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (55, 'RC Lens', 4);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (56, 'Al Fayha', 7);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (57, 'Frankfurt', 3);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (58, 'Como', 5);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (59, 'FC Cincinnati', 6);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (60, 'SC Braga', 8);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (61, 'LOSC Lille', 4);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (62, 'PSV', 3);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (63, 'Crystal Palace', 2);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (64, 'Bologna', 5);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (65, 'AS Monaco', 3);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (66, 'Feyenoord', 3);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (67, 'Brighton', 2);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (68, 'Rayo Vallecano', 1);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (69, 'Southampton', 2);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (70, 'Trabzonspor', 7);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (71, 'Getafe CF', 1);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (72, 'VfB Stuttgart', 3);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (73, 'UD Las Palmas', 1);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (74, 'Royal Antwerp FC', 13);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (75, 'VfL Wolfsburg', 3);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (76, 'OGC Nice', 4);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (77, 'AFC Bournemouth', 2);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (78, 'Lecce', 5);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (79, 'Sevilla FC', 1);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (80, 'Ettifaq FC', 7);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (81, 'Fiorentina', 5);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (82, 'Ajax', 3);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (83, 'OM', 1);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (84, 'Brentford', 2);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (85, 'Hajduk Split', 14);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (86, 'Montpellier', 1);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (87, 'Celtic', 15);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (88, 'FC Twente', 3);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (89, 'Club Brugge', 13);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (90, 'Al Fateh', 7);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (91, 'Wolves', 2);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (92, 'Newell''s', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (93, 'Stade Brestois 29', 1);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (94, 'CA Osasuna', 1);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (95, 'AZ', 3);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (96, 'Red Bulls', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (97, 'Nott''m Forest', 2);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (98, 'New England', 6);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (99, 'CD Leganés', 1);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (100, 'M''gladbach', 3);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (101, 'AEK Athens', 17);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (102, 'Nashville SC', 6);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (103, 'Monza', 5);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (104, 'Strasbourg', 4);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (105, 'Al Ain FC', 18);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (106, 'Union Berlin', 3);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (107, '1. FSV Mainz 05', 3);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (108, 'Real Salt Lake', 6);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (109, 'Leicester City', 2);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (110, 'Sparta Praha', 19);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (111, 'St. Louis CITY SC', 6);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (112, 'Ferencvárosi TC', 20);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (113, 'Slavia Praha', 19);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (114, 'Shanghai Port FC', 21);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (115, 'Olympiacos FC', 17);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (116, 'Al Taawoun', 7);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (117, 'Whitecaps FC', 6);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (118, 'Stade Rennais FC', 4);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (119, 'Columbus Crew', 6);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (120, 'Houston Dynamo', 6);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (121, 'Toronto FC', 6);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (122, 'Stade de Reims', 4);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (123, 'D. Alavés', 1);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (124, 'Panathinaikos', 17);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (125, 'Orlando City', 6);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (126, 'LA Galaxy', 6);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (127, 'Toulouse FC', 4);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (128, 'Boca Juniors', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (129, 'Dynamo Kyiv', 23);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (130, 'Rangers', 15);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (131, 'RSC Anderlecht', 13);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (132, 'PAOK FC', 17);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (133, 'Al Orobah', 7);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (134, 'UD Almería', 1);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (135, 'RB Salzburg', 25);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (136, 'Portland Timbers', 6);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (137, 'Luton Town', 2);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (138, 'Austin FC', 6);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (139, 'SV Werder Bremen', 3);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (140, 'Al Kholood', 7);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (141, 'KRC Genk', 13);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (142, 'FC Dallas', 6);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (143, 'Cagliari', 5);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (144, 'R. Valladolid CF', 1);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (145, 'Genoa', 5);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (146, 'Hellas Verona', 5);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (147, 'Lanús', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (148, 'FC Lorient', 4);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (149, 'Damac FC', 7);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (150, 'Atl. Nacional', 28);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (151, 'Dinamo Zagreb', 14);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (152, 'Ipswich', 2);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (153, 'RCD Espanyol', 1);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (154, 'Racing Club', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (155, '1. FC Köln', 3);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (156, 'Shakhtar Donetsk', 23);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (157, 'Leeds United', 26);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (158, 'Sunderland', 26);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (159, 'Estudiantes', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (160, 'Parma', 5);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (161, 'Junior', 28);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (162, 'FK Bodø/Glimt', 30);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (163, 'Burnley', 26);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (164, 'Granada CF', 1);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (165, 'San Lorenzo', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (166, 'R. Union St.-G.', 13);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (167, 'Rosario Central', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (168, 'FC Nantes', 4);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (169, 'Chicago Fire FC', 6);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (170, 'Başakşehir', 11);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (171, 'Empoli', 5);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (172, 'F.C. København', 31);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (173, 'Cercle Brugge', 13);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (174, 'Peñarol', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (175, 'Cádiz CF', 1);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (176, 'FC Augsburg', 3);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (177, 'Hannover 96', 29);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (178, 'Sheffield Utd', 26);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (179, 'Konyaspor', 11);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (180, 'Talleres', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (181, 'Paris FC', 27);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (182, 'Vitória SC', 8);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (183, 'Heidenheim', 3);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (184, 'Sivasspor', 11);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (185, 'FC Midtjylland', 31);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (186, 'Sounders FC', 6);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (187, 'Millonarios', 28);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (188, 'Levante UD', 24);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (189, 'Sparta Rotterdam', 12);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (190, 'Shandong Taishan', 21);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (191, 'VfL Bochum 1848', 3);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (192, 'N.E.C. Nijmegen', 12);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (193, 'Vélez Sarsfield', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (194, 'Al Khaleej', 7);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (195, 'Sampdoria', 10);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (196, 'FC Famalicão', 8);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (197, 'Sp. Charleroi', 13);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (198, 'AS Saint-Étienne', 27);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (199, 'Pohang Steelers', 32);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (200, 'Udinese', 5);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (201, 'Philadelphia', 6);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (202, 'Barcelona SC', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (203, 'R. Oviedo', 24);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (204, 'Casa Pia AC', 8);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (205, 'R. Sporting', 24);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (206, 'Gil Vicente', 8);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (207, 'Rio Ave FC', 8);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (208, 'Havre AC', 4);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (209, 'Palermo', 10);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (210, 'Clermont Foot 63', 4);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (211, 'Elche CF', 24);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (212, 'LDU Quito', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (213, 'FK Austria Wien', 25);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (214, 'Molde FK', 30);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (215, 'Al Wehda', 7);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (216, 'SJ Earthquakes', 6);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (217, 'Arouca', 8);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (218, 'FC Seoul', 32);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (219, 'Ulsan Hyundai', 32);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (220, 'Minnesota United', 6);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (221, 'Zhejiang Pro', 21);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (222, 'Independiente', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (223, 'Gaziantep', 11);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (224, 'RC Deportivo', 24);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (225, 'Venezia', 5);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (226, 'Hertha BSC', 29);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (227, 'Estoril Praia', 8);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (228, 'Alianza Lima', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (229, 'Argentinos Jrs.', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (230, 'Adana Demirspor', 11);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (231, 'KV Mechelen', 13);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (232, 'Hearts', 15);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (233, 'Coventry City', 26);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (234, 'IDV', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (235, 'Brøndby IF', 31);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (236, 'FC Lugano', 25);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (237, 'Servette FC', 25);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (238, 'Viktoria Plzeň', 19);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (239, 'AJ Auxerre', 27);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (240, 'Cremonese', 10);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (241, 'R. Racing Club', 24);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (242, 'LASK', 25);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (243, 'Charlotte FC', 6);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (244, 'SD Eibar', 24);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (245, 'Real Zaragoza', 24);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (246, 'FC Utrecht', 12);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (247, 'D.C. United', 6);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (248, 'Standard Liège', 13);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (249, 'Stoke City', 26);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (250, 'Blackburn Rovers', 26);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (251, 'Südtirol', 10);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (252, 'QPR', 26);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (253, 'Cardiff City', 26);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (254, 'Colo-Colo', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (255, 'Gimnasia', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (256, 'Moreirense FC', 8);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (257, 'KV Kortrijk', 13);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (258, 'Banfield', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (259, 'U. Católica', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (260, 'Huracán', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (261, 'BSC Young Boys', 25);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (262, 'Cerro Porteño', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (263, 'Belgrano', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (264, 'Al Raed', 7);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (265, 'Kasımpaşa', 11);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (266, 'Hamburger SV', 29);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (267, 'SK Sturm Graz', 25);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (268, 'Pogoń Szczecin', 34);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (269, 'Norwich', 26);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (270, 'Çaykur Rizespor', 11);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (271, 'FC Metz', 4);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (272, 'FC Basel 1893', 25);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (273, 'Holstein Kiel', 29);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (274, 'FC St. Pauli', 29);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (275, 'Alanyaspor', 11);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (276, '1. FC Nürnberg', 29);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (277, 'KAA Gent', 13);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (278, 'Gimcheon Sangmu', 32);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (279, 'Daejeon', 32);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (280, 'Instituto', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (281, 'Sydney FC', 35);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (282, 'Salernitana', 10);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (283, 'Hull City', 26);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (284, 'Colorado Rapids', 6);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (285, 'Beijing FC', 21);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (286, 'Godoy Cruz', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (287, 'BK Häcken', 36);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (288, 'Eyüpspor', 11);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (289, 'SV Darmstadt 98', 3);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (290, 'Libertad', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (291, 'Daegu FC', 32);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (292, 'Changchun Yatai', 21);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (293, 'Samsunspor', 11);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (294, 'West Brom', 26);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (295, 'Preston', 26);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (296, 'Plymouth Argyle', 26);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (297, 'Uni. Católica', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (298, 'Boavista FC', 8);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (299, 'Angers SCO', 27);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (300, 'Pisa', 10);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (301, 'Kaiserslautern', 29);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (302, 'FC St. Gallen', 25);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (303, 'Estrela Amadora', 8);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (304, 'Shanghai Shenhua', 21);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (305, 'Reggiana', 10);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (306, 'APOEL FC', 37);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (307, 'Ind. Rivadavia', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (308, 'Millwall', 26);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (309, 'Unión', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (310, 'Malmö FF', 36);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (311, 'Djurgårdens IF', 36);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (312, 'Rongcheng FC', 21);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (313, 'Racing de Ferrol', 24);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (314, 'Qarabağ FK', 38);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (315, 'Lausanne-Sport', 25);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (316, 'Hatayspor', 11);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (317, 'Olimpia', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (318, 'Deportes Tolima', 28);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (319, 'FC Nordsjælland', 31);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (320, 'FC Schalke 04', 29);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (321, 'Bolívar', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (322, 'Melbourne City', 35);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (323, 'Göztepe', 11);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (324, 'Raków', 34);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (325, 'PEC Zwolle', 12);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (326, 'SM Caen', 27);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (327, 'Univ. Craiova', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (328, 'Huachipato', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (329, 'New York City FC', 6);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (330, 'Middlesbrough', 26);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (331, 'América de Cali', 28);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (332, 'Incheon United', 32);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (333, 'Al Okhdood', 7);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (334, 'sc Heerenveen', 12);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (335, 'FCSB', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (336, 'Frosinone', 10);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (337, 'Nacional', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (338, 'Spezia', 10);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (339, 'Auckland FC', 35);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (340, 'Farense', 8);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (341, 'Watford', 26);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (342, 'AGF', 31);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (343, 'Viking FK', 30);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (344, 'Tianjin JMT FC', 21);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (345, 'Karlsruher SC', 29);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (346, 'Atlanta United', 6);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (347, 'Henan FC', 21);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (348, 'Sportivo Luqueño', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (349, 'Düsseldorf', 29);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (350, 'Kilmarnock', 15);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (351, 'Sheffield Wed', 26);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (352, 'Swansea City', 26);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (353, 'Defensa', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (354, 'Qingdao W. Coast', 21);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (355, 'SK Rapid', 25);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (356, 'Grenoble Foot 38', 27);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (357, 'Yverdon Sport FC', 25);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (358, 'Braunschweig', 29);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (359, 'Birmingham City', 26);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (360, 'Modena', 10);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (361, 'FC Zürich', 25);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (362, 'Kayserispor', 11);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (363, 'CF Montréal', 6);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (364, 'CD Tenerife', 24);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (365, 'Catanzaro', 10);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (366, 'Qingdao Hainiu', 21);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (367, 'Platense', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (368, 'Bristol City', 26);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (369, 'Bari', 10);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (370, 'Santa Clara', 8);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (371, 'Macarthur FC', 35);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (372, 'Widzew Łódź', 34);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (373, 'Preußen Münster', 42);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (374, 'Bodrum FK', 11);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (375, 'Fürth', 29);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (376, 'Jagiellonia', 34);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (377, 'Sarmiento', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (378, 'IFK Norrköping', 36);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (379, 'Antalyaspor', 11);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (380, 'Jeonbuk Hyundai', 32);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (381, 'Málaga CF', 24);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (382, 'Cangzhou FC', 21);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (383, 'OH Leuven', 13);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (384, 'Bengaluru FC', 33);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (385, 'Suwon FC', 32);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (386, 'Indep. Medellín', 28);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (387, 'Dep. Cuenca', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (388, 'Górnik Zabrze', 34);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (389, 'Universitario', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (390, 'Sporting KC', 6);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (391, 'SD Huesca', 24);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (392, 'Atlético Tucumán', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (393, 'Lech Poznań', 34);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (394, 'Rosenborg BK', 30);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (395, 'KVC Westerlo', 13);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (396, 'STVV', 13);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (397, 'The Strongest', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (398, 'IF Elfsborg', 36);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (399, 'CD Castellón', 24);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (400, '1. FC Magdeburg', 29);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (401, 'Jeju United', 32);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (402, 'Cesena', 10);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (403, 'Wolfsberger AC', 25);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (404, 'Hammarby IF', 36);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (405, 'Brescia', 10);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (406, 'Hibernian', 15);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (407, 'Fortuna Sittard', 12);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (408, 'Coquimbo Unido', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (409, 'Derby County', 26);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (410, 'Albacete BP', 24);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (411, 'Burgos CF', 24);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (412, 'FC Winterthur', 25);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (413, 'East Bengal', 33);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (414, 'AVS Futebol SAD', 8);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (415, 'SZ Peng City', 21);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (416, 'Wuhan Three Towns', 21);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (417, 'Danubio', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (418, 'Tigre', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (419, 'Wanderers', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (420, 'Huddersfield', 26);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (421, 'GwangJu FC', 32);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (422, 'FC Luzern', 25);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (423, 'Meizhou Hakka FC', 21);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (424, 'FC Sion', 25);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (425, 'UCV', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (426, 'Cosenza', 10);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (427, 'SC Paderborn 07', 29);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (428, 'Barracas Central', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (429, 'GC Zürich', 25);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (430, 'Aberdeen', 15);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (431, 'Legia Warszawa', 34);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (432, 'Brisbane Roar', 35);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (433, 'Sport Huancayo', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (434, 'Randers FC', 31);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (435, 'USL Dunkerque', 27);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (436, 'Palestino', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (437, 'FC Groningen', 12);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (438, 'Cobresal', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (439, 'Adelaide United', 35);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (440, 'Farul Constanța', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (441, 'Técnico U.', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (442, 'TSV Hartberg', 25);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (443, 'Always Ready', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (444, 'Odisha FC', 33);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (445, 'Cittadella', 10);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (446, 'Oxford United', 40);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (447, 'Zagłębie Lubin', 34);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (448, 'Red Star FC', 27);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (449, 'Wrexham', 40);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (450, 'Go Ahead Eagles', 12);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (451, 'Caracas FC', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (452, 'CD Mirandés', 24);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (453, 'SK Brann', 30);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (454, 'Amiens SC', 27);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (455, 'Cerro Largo', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (456, 'Nacional Potosí', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (457, 'CD Eldense', 24);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (458, 'FC Rapid 1923', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (459, 'Central Coast', 35);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (460, 'Pau FC', 27);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (461, 'Melb. Victory', 35);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (462, 'FC Cartagena', 24);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (463, 'FC Univ. Cluj', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (464, 'Central Córdoba', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (465, 'AIK', 36);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (466, 'Laval MFC', 27);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (467, 'Arminia Bielefeld', 42);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (468, 'Guaraní', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (469, 'Stal Mielec', 34);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (470, 'Silkeborg IF', 31);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (471, 'SCR Altach', 25);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (472, 'Wehen Wiesbaden', 29);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (473, 'CFR 1907 Cluj', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (474, 'Perth Glory', 35);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (475, 'FC Hansa Rostock', 42);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (476, 'Reading', 40);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (477, 'RKC Waalwijk', 12);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (478, 'Bolton', 40);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (479, 'Mantova', 10);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (480, 'Dep. Táchira', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (481, 'IFK Göteborg', 36);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (482, 'Śląsk Wrocław', 34);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (483, 'FC Ingolstadt 04', 42);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (484, 'Portsmouth', 40);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (485, 'WS Wanderers', 35);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (486, 'Charlton Ath', 40);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (487, 'St. Johnstone', 15);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (488, 'ESTAC Troyes', 27);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (489, 'Rotherham Utd', 40);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (490, 'Dep. Garcilaso', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (491, 'Mohun Bagan SG', 33);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (492, 'VfL Osnabrück', 42);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (493, 'Jamshedpur FC', 33);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (494, 'Unión La Calera', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (495, 'Grazer AK', 25);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (496, 'Metropolitanos', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (497, 'Lillestrøm SK', 30);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (498, 'Rot-Weiss Essen', 42);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (499, 'Odds BK', 30);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (500, 'Dynamo Dresden', 42);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (501, 'Dep. Riestra', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (502, 'SV Elversberg', 29);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (503, 'NAC Breda', 12);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (504, 'Sarpsborg 08', 30);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (505, 'Nantong Zhiyun FC', 21);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (506, 'Jahn Regensburg', 42);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (507, 'FCV Dender EH', 13);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (508, 'Wycombe', 40);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (509, 'Gangwon FC', 32);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (510, 'Viborg FF', 31);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (511, 'Austria Klagenfurt', 25);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (512, 'AC Ajaccio', 27);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (513, 'Willem II', 12);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (514, 'Sepsi OSK', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (515, 'GKS Katowice', 34);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (516, 'Peterborough', 40);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (517, 'Motor Lublin', 34);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (518, 'K. Beerschot VA', 13);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (519, 'Carrarese Calcio', 10);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (520, 'FK Haugesund', 30);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (521, 'Strømsgodset IF', 30);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (522, 'WSG Tirol', 25);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (523, 'Wilstermann', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (524, 'AaB', 31);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (525, 'Cracovia', 34);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (526, 'KFUM-Kameratene', 30);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (527, 'FC Martigues', 27);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (528, 'Mansfield Town', 44);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (529, 'Punjab FC', 33);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (530, 'Almere City FC', 12);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (531, 'Well. Phoenix', 35);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (532, 'En Avant Guingamp', 27);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (533, 'Alianza FC', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (534, 'SV Waldhof', 42);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (535, 'FC Dinamo 1948', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (536, 'Shamrock Rovers', 43);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (537, 'SC Oțelul Galați', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (538, 'Vejle Boldklub', 31);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (539, 'Piast Gliwice', 34);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (540, 'FC Goa', 33);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (541, 'SC Bastia', 27);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (542, 'IFK Värnamo', 36);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (543, 'Lincoln City', 40);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (544, 'SSV Ulm 1846', 42);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (545, 'Western United', 35);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (546, 'Blau-Weiss Linz', 25);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (547, 'Carabobo FC', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (548, 'Northampton', 40);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (549, 'Heracles Almelo', 12);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (550, 'Barnsley', 40);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (551, 'Blackpool', 40);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (552, 'Notts County', 44);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (553, 'Mumbai City FC', 33);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (554, 'Kerala Blasters', 33);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (555, 'FC Erzgebirge Aue', 42);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (556, 'Córdoba CF', 24);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (557, 'Saarbrücken', 42);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (558, 'Exeter City', 40);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (559, 'Rodez AF', 27);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (560, 'Brommapojkarna', 36);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (561, 'St. Mirren', 15);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (562, 'S. Ameliano', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (563, 'Stevenage', 40);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (564, 'ADT', 33);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (565, 'Wigan Athletic', 40);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (566, 'Motherwell', 15);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (567, 'Dep. La Guaira', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (568, '1860 München', 42);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (569, 'FC Petrolul', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (570, 'Club Nacional', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (571, 'FC Hermannstadt', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (572, 'SV Sandhausen', 42);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (573, 'FC Gloria Buzău', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (574, 'Chennaiyin FC', 33);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (575, 'S. Trinidense', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (576, 'Chesterfield', 44);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (577, 'FC Annecy', 27);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (578, 'NorthEast United', 33);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (579, 'FC Botoșani', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (580, 'Radomiak Radom', 34);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (581, 'B. Dortmund II', 42);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (582, 'Kalmar FF', 36);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (583, 'Tromsø IL', 30);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (584, 'Colchester', 44);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (585, 'Delfín SC', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (586, 'SS Juve Stabia', 10);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (587, 'Mjällby AIF', 36);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (588, 'Korona Kielce', 34);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (589, 'Politehnica Iași', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (590, 'HJK Helsinki', 45);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (591, 'Doncaster', 40);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (592, 'Dundee United', 15);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (593, 'Dundee FC', 15);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (594, 'Puszcza', 34);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (595, 'Lyngby BK', 31);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (596, 'Al Riyadh', 7);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (597, 'UTA Arad', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (598, 'SC Verl', 42);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (599, 'Halmstads BK', 36);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (600, 'Cambridge Utd', 40);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (601, 'Fredrikstad FK', 30);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (602, 'Lechia Gdańsk', 34);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (603, 'Sønderjyske', 31);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (604, 'Port Vale', 40);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (605, 'Galway United', 43);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (606, 'Bristol Rovers', 40);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (607, 'St. Pats', 43);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (608, 'Aleman. Aachen', 42);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (609, 'Leyton Orient', 40);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (610, 'Real Tomayapo', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (611, 'Bradford City', 44);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (612, 'Viktoria Köln', 42);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (613, 'Stockport', 44);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (614, 'Shelbourne', 43);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (615, 'MK Dons', 44);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (616, 'Unterhaching', 42);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (617, 'Fleetwood Town', 40);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (618, 'Shrewsbury', 40);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (619, 'HamKam Fotball', 30);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (620, 'Salford City', 44);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (621, 'Carlisle United', 44);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (622, 'Burton Albion', 40);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (623, 'Energie Cottbus', 42);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (624, 'Crewe Alexandra', 44);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (625, 'Derry City', 43);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (626, 'Walsall', 44);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (627, 'Swindon Town', 44);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (628, 'Gillingham', 44);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (629, 'Barrow', 44);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (630, 'Sligo Rovers', 43);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (631, 'Sandefjord', 30);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (632, 'IK Sirius', 36);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (633, 'Unirea Slobozia', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (634, 'Newcastle Jets', 35);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (635, 'VfB Stuttgart II', 42);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (636, 'Rayo Zuliano', 9);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (637, 'Crawley Town', 44);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (638, 'Morecambe', 44);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (639, 'Västerås SK', 36);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (640, 'AFC Wimbledon', 44);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (641, 'Ross County', 15);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (642, 'Kristiansund BK', 30);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (643, 'GAIS', 36);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (644, 'Tranmere Rovers', 44);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (645, 'Harrogate Town', 44);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (646, 'Cheltenham Town', 44);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (647, 'Bromley FC', 44);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (648, 'Bohemians', 43);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (649, 'Hannover 96 II', 42);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (650, 'Grimsby Town', 44);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (651, 'Newport County', 44);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (652, 'Accrington', 44);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (653, 'Waterford', 43);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (654, 'Dundalk', 43);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (655, 'Drogheda United', 43);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (656, 'Mohammedan SC', 33);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES (657, 'Hyderabad FC', 33);
INSERT INTO jugadores (id_equipo, equipo, id_liga) VALUES ();
